services:
  nginx:
    image: nginx:alpine
    container_name: notarity-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - api
    restart: always

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notarity-api
    env_file:
      - .env
    volumes:
      - ./notarity.db:/app/notarity.db
    restart: always

  frontend:
    build: ./frontend
    container_name: notarity-frontend
    env_file:
      - .env
    restart: always
